spring.application.name: form-excercise-server
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/alo_test_db?allowPublicKeyRetrieval=true&useSSL=false
    username: app_user
    password: ${DB_PASSWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true



